/*
 * generated by Xtext 2.18.0.M3
 */
package hu.sze.aut.diffrobot.dse.ide


/**
 * Use this class to register ide components.
 */
class DiffRobotDslIdeModule extends AbstractDiffRobotDslIdeModule {
}
