/*
 * generated by Xtext 2.18.0.M3
 */
package hu.sze.aut.diffrobot.dse


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DiffRobotDslRuntimeModule extends AbstractDiffRobotDslRuntimeModule {
}
