/*
 * generated by Xtext 2.18.0.M3
 */
package hu.sze.aut.diffrobot.dse


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DiffRobotDslStandaloneSetup extends DiffRobotDslStandaloneSetupGenerated {

	def static void doSetup() {
		new DiffRobotDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
