/*
 * generated by Xtext 2.21.0
 */
package hu.sze.aut.fuzzy.hybrid.system.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import hu.sze.aut.fuzzy.hybrid.system.ide.contentassist.antlr.internal.InternalFuzzyDslParser;
import hu.sze.aut.fuzzy.hybrid.system.services.FuzzyDslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class FuzzyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(FuzzyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, FuzzyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getConVariableAccess().getAlternatives(), "rule__ConVariable__Alternatives");
			builder.put(grammarAccess.getMembershipFunctionAccess().getAlternatives(), "rule__MembershipFunction__Alternatives");
			builder.put(grammarAccess.getRuleSetAccess().getAlternatives(), "rule__RuleSet__Alternatives");
			builder.put(grammarAccess.getRuleAccess().getAlternatives(), "rule__Rule__Alternatives");
			builder.put(grammarAccess.getRelationExpressionAccess().getAlternatives(), "rule__RelationExpression__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getSimpleSystemAccess().getGroup(), "rule__SimpleSystem__Group__0");
			builder.put(grammarAccess.getSimpleSystemAccess().getGroup_3(), "rule__SimpleSystem__Group_3__0");
			builder.put(grammarAccess.getSimpleSystemAccess().getGroup_9(), "rule__SimpleSystem__Group_9__0");
			builder.put(grammarAccess.getSimpleSystemAccess().getGroup_18(), "rule__SimpleSystem__Group_18__0");
			builder.put(grammarAccess.getContinuousVariableAccess().getGroup(), "rule__ContinuousVariable__Group__0");
			builder.put(grammarAccess.getClockAccess().getGroup(), "rule__Clock__Group__0");
			builder.put(grammarAccess.getFuzzySetAccess().getGroup(), "rule__FuzzySet__Group__0");
			builder.put(grammarAccess.getAlphaAccess().getGroup(), "rule__Alpha__Group__0");
			builder.put(grammarAccess.getLambdaAccess().getGroup(), "rule__Lambda__Group__0");
			builder.put(grammarAccess.getTrapezoidAccess().getGroup(), "rule__Trapezoid__Group__0");
			builder.put(grammarAccess.getDiscreteEventRulesetAccess().getGroup(), "rule__DiscreteEventRuleset__Group__0");
			builder.put(grammarAccess.getDiscreteEventRulesetAccess().getGroup_3(), "rule__DiscreteEventRuleset__Group_3__0");
			builder.put(grammarAccess.getDiscreteEventRulesetAccess().getGroup_3_2(), "rule__DiscreteEventRuleset__Group_3_2__0");
			builder.put(grammarAccess.getContinuousEventRuleSetAccess().getGroup(), "rule__ContinuousEventRuleSet__Group__0");
			builder.put(grammarAccess.getDiscreteEventAccess().getGroup(), "rule__DiscreteEvent__Group__0");
			builder.put(grammarAccess.getCrispGuardAccess().getGroup(), "rule__CrispGuard__Group__0");
			builder.put(grammarAccess.getGreaterExpressionAccess().getGroup(), "rule__GreaterExpression__Group__0");
			builder.put(grammarAccess.getLessExpressionAccess().getGroup(), "rule__LessExpression__Group__0");
			builder.put(grammarAccess.getFuzzyRuleAccess().getGroup(), "rule__FuzzyRule__Group__0");
			builder.put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
			builder.put(grammarAccess.getLocationAccess().getGroup_3(), "rule__Location__Group_3__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_9(), "rule__Transition__Group_9__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_10(), "rule__Transition__Group_10__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup_4(), "rule__Action__Group_4__0");
			builder.put(grammarAccess.getSimpleSystemAccess().getNameAssignment_2(), "rule__SimpleSystem__NameAssignment_2");
			builder.put(grammarAccess.getSimpleSystemAccess().getRateAssignment_3_3(), "rule__SimpleSystem__RateAssignment_3_3");
			builder.put(grammarAccess.getSimpleSystemAccess().getLocationAssignment_6(), "rule__SimpleSystem__LocationAssignment_6");
			builder.put(grammarAccess.getSimpleSystemAccess().getLocationAssignment_7(), "rule__SimpleSystem__LocationAssignment_7");
			builder.put(grammarAccess.getSimpleSystemAccess().getFuzzysetAssignment_9_1(), "rule__SimpleSystem__FuzzysetAssignment_9_1");
			builder.put(grammarAccess.getSimpleSystemAccess().getFuzzysetAssignment_9_2(), "rule__SimpleSystem__FuzzysetAssignment_9_2");
			builder.put(grammarAccess.getSimpleSystemAccess().getRulesetAssignment_11(), "rule__SimpleSystem__RulesetAssignment_11");
			builder.put(grammarAccess.getSimpleSystemAccess().getRulesetAssignment_12(), "rule__SimpleSystem__RulesetAssignment_12");
			builder.put(grammarAccess.getSimpleSystemAccess().getActiondefinitionAssignment_15(), "rule__SimpleSystem__ActiondefinitionAssignment_15");
			builder.put(grammarAccess.getSimpleSystemAccess().getActiondefinitionAssignment_16(), "rule__SimpleSystem__ActiondefinitionAssignment_16");
			builder.put(grammarAccess.getSimpleSystemAccess().getVariableAssignment_18_1(), "rule__SimpleSystem__VariableAssignment_18_1");
			builder.put(grammarAccess.getSimpleSystemAccess().getVariableAssignment_18_2(), "rule__SimpleSystem__VariableAssignment_18_2");
			builder.put(grammarAccess.getSimpleSystemAccess().getTransitionAssignment_20(), "rule__SimpleSystem__TransitionAssignment_20");
			builder.put(grammarAccess.getSimpleSystemAccess().getTransitionAssignment_21(), "rule__SimpleSystem__TransitionAssignment_21");
			builder.put(grammarAccess.getSimpleSystemAccess().getStartlocationAssignment_25(), "rule__SimpleSystem__StartlocationAssignment_25");
			builder.put(grammarAccess.getSimpleSystemAccess().getErrorlocationAssignment_27(), "rule__SimpleSystem__ErrorlocationAssignment_27");
			builder.put(grammarAccess.getContinuousVariableAccess().getNameAssignment_2(), "rule__ContinuousVariable__NameAssignment_2");
			builder.put(grammarAccess.getClockAccess().getNameAssignment_2(), "rule__Clock__NameAssignment_2");
			builder.put(grammarAccess.getFuzzySetAccess().getNameAssignment_2(), "rule__FuzzySet__NameAssignment_2");
			builder.put(grammarAccess.getFuzzySetAccess().getMembershipfunctionAssignment_3(), "rule__FuzzySet__MembershipfunctionAssignment_3");
			builder.put(grammarAccess.getFuzzySetAccess().getMembershipfunctionAssignment_4(), "rule__FuzzySet__MembershipfunctionAssignment_4");
			builder.put(grammarAccess.getAlphaAccess().getNameAssignment_2(), "rule__Alpha__NameAssignment_2");
			builder.put(grammarAccess.getAlphaAccess().getVariableAssignment_4(), "rule__Alpha__VariableAssignment_4");
			builder.put(grammarAccess.getAlphaAccess().getAAssignment_6(), "rule__Alpha__AAssignment_6");
			builder.put(grammarAccess.getAlphaAccess().getBAssignment_8(), "rule__Alpha__BAssignment_8");
			builder.put(grammarAccess.getLambdaAccess().getNameAssignment_2(), "rule__Lambda__NameAssignment_2");
			builder.put(grammarAccess.getLambdaAccess().getVariableAssignment_4(), "rule__Lambda__VariableAssignment_4");
			builder.put(grammarAccess.getLambdaAccess().getAAssignment_6(), "rule__Lambda__AAssignment_6");
			builder.put(grammarAccess.getLambdaAccess().getUAssignment_8(), "rule__Lambda__UAssignment_8");
			builder.put(grammarAccess.getLambdaAccess().getBAssignment_10(), "rule__Lambda__BAssignment_10");
			builder.put(grammarAccess.getTrapezoidAccess().getNameAssignment_2(), "rule__Trapezoid__NameAssignment_2");
			builder.put(grammarAccess.getTrapezoidAccess().getVariableAssignment_4(), "rule__Trapezoid__VariableAssignment_4");
			builder.put(grammarAccess.getTrapezoidAccess().getAAssignment_6(), "rule__Trapezoid__AAssignment_6");
			builder.put(grammarAccess.getTrapezoidAccess().getBAssignment_8(), "rule__Trapezoid__BAssignment_8");
			builder.put(grammarAccess.getDiscreteEventRulesetAccess().getNameAssignment_2(), "rule__DiscreteEventRuleset__NameAssignment_2");
			builder.put(grammarAccess.getDiscreteEventRulesetAccess().getDiscreteeventAssignment_3_1(), "rule__DiscreteEventRuleset__DiscreteeventAssignment_3_1");
			builder.put(grammarAccess.getDiscreteEventRulesetAccess().getDiscreteeventAssignment_3_2_1(), "rule__DiscreteEventRuleset__DiscreteeventAssignment_3_2_1");
			builder.put(grammarAccess.getContinuousEventRuleSetAccess().getNameAssignment_2(), "rule__ContinuousEventRuleSet__NameAssignment_2");
			builder.put(grammarAccess.getContinuousEventRuleSetAccess().getRuleAssignment_4(), "rule__ContinuousEventRuleSet__RuleAssignment_4");
			builder.put(grammarAccess.getContinuousEventRuleSetAccess().getRuleAssignment_5(), "rule__ContinuousEventRuleSet__RuleAssignment_5");
			builder.put(grammarAccess.getDiscreteEventAccess().getNameAssignment_2(), "rule__DiscreteEvent__NameAssignment_2");
			builder.put(grammarAccess.getCrispGuardAccess().getNameAssignment_2(), "rule__CrispGuard__NameAssignment_2");
			builder.put(grammarAccess.getCrispGuardAccess().getRelationexpressionAssignment_4(), "rule__CrispGuard__RelationexpressionAssignment_4");
			builder.put(grammarAccess.getGreaterExpressionAccess().getVariableAssignment_1(), "rule__GreaterExpression__VariableAssignment_1");
			builder.put(grammarAccess.getGreaterExpressionAccess().getCAssignment_3(), "rule__GreaterExpression__CAssignment_3");
			builder.put(grammarAccess.getLessExpressionAccess().getVariableAssignment_1(), "rule__LessExpression__VariableAssignment_1");
			builder.put(grammarAccess.getLessExpressionAccess().getCAssignment_3(), "rule__LessExpression__CAssignment_3");
			builder.put(grammarAccess.getLocationAccess().getNameAssignment_2(), "rule__Location__NameAssignment_2");
			builder.put(grammarAccess.getLocationAccess().getCyclicactionAssignment_3_1(), "rule__Location__CyclicactionAssignment_3_1");
			builder.put(grammarAccess.getTransitionAccess().getNameAssignment_2(), "rule__Transition__NameAssignment_2");
			builder.put(grammarAccess.getTransitionAccess().getSourceAssignment_4(), "rule__Transition__SourceAssignment_4");
			builder.put(grammarAccess.getTransitionAccess().getTargetAssignment_6(), "rule__Transition__TargetAssignment_6");
			builder.put(grammarAccess.getTransitionAccess().getTriggerAssignment_8(), "rule__Transition__TriggerAssignment_8");
			builder.put(grammarAccess.getTransitionAccess().getActiondefinitionAssignment_9_1(), "rule__Transition__ActiondefinitionAssignment_9_1");
			builder.put(grammarAccess.getTransitionAccess().getInvariantAssignment_10_1(), "rule__Transition__InvariantAssignment_10_1");
			builder.put(grammarAccess.getActionAccess().getNameAssignment_3(), "rule__Action__NameAssignment_3");
			builder.put(grammarAccess.getActionAccess().getResetAssignment_4_1(), "rule__Action__ResetAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private FuzzyDslGrammarAccess grammarAccess;

	@Override
	protected InternalFuzzyDslParser createParser() {
		InternalFuzzyDslParser result = new InternalFuzzyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public FuzzyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FuzzyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
