/*
 * generated by Xtext 2.21.0
 */
package hu.sze.aut.fuzzy.hybrid.system.ide;


/**
 * Use this class to register ide components.
 */
public class FuzzyDslIdeModule extends AbstractFuzzyDslIdeModule {
}
