/*
 * generated by Xtext 2.21.0
 */
grammar InternalFuzzyDsl;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package hu.sze.aut.fuzzy.hybrid.system.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package hu.sze.aut.fuzzy.hybrid.system.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import hu.sze.aut.fuzzy.hybrid.system.services.FuzzyDslGrammarAccess;

}

@parser::members {

 	private FuzzyDslGrammarAccess grammarAccess;

    public InternalFuzzyDslParser(TokenStream input, FuzzyDslGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "HybridSystem";
   	}

   	@Override
   	protected FuzzyDslGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleHybridSystem
entryRuleHybridSystem returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getHybridSystemRule()); }
	iv_ruleHybridSystem=ruleHybridSystem
	{ $current=$iv_ruleHybridSystem.current; }
	EOF;

// Rule HybridSystem
ruleHybridSystem returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	{
		newCompositeNode(grammarAccess.getHybridSystemAccess().getSimpleSystemParserRuleCall());
	}
	this_SimpleSystem_0=ruleSimpleSystem
	{
		$current = $this_SimpleSystem_0.current;
		afterParserOrEnumRuleCall();
	}
;

// Entry rule entryRuleSimpleSystem
entryRuleSimpleSystem returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSimpleSystemRule()); }
	iv_ruleSimpleSystem=ruleSimpleSystem
	{ $current=$iv_ruleSimpleSystem.current; }
	EOF;

// Rule SimpleSystem
ruleSimpleSystem returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getSimpleSystemAccess().getSystemAction_0(),
					$current);
			}
		)
		otherlv_1='hybridsystem'
		{
			newLeafNode(otherlv_1, grammarAccess.getSimpleSystemAccess().getHybridsystemKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSimpleSystemAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_3=','
			{
				newLeafNode(otherlv_3, grammarAccess.getSimpleSystemAccess().getCommaKeyword_3_0());
			}
			otherlv_4='rate'
			{
				newLeafNode(otherlv_4, grammarAccess.getSimpleSystemAccess().getRateKeyword_3_1());
			}
			otherlv_5=':'
			{
				newLeafNode(otherlv_5, grammarAccess.getSimpleSystemAccess().getColonKeyword_3_2());
			}
			(
				(
					lv_rate_6_0=RULE_DOUBLE
					{
						newLeafNode(lv_rate_6_0, grammarAccess.getSimpleSystemAccess().getRateDOUBLETerminalRuleCall_3_3_0());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getSimpleSystemRule());
						}
						setWithLastConsumed(
							$current,
							"rate",
							lv_rate_6_0,
							"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.DOUBLE");
					}
				)
			)
		)?
		otherlv_7='locations'
		{
			newLeafNode(otherlv_7, grammarAccess.getSimpleSystemAccess().getLocationsKeyword_4());
		}
		otherlv_8=':'
		{
			newLeafNode(otherlv_8, grammarAccess.getSimpleSystemAccess().getColonKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSimpleSystemAccess().getLocationLocationParserRuleCall_6_0());
				}
				lv_location_9_0=ruleLocation
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
					}
					add(
						$current,
						"location",
						lv_location_9_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.Location");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getSimpleSystemAccess().getLocationLocationParserRuleCall_7_0());
				}
				lv_location_10_0=ruleLocation
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
					}
					add(
						$current,
						"location",
						lv_location_10_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.Location");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_11='end'
		{
			newLeafNode(otherlv_11, grammarAccess.getSimpleSystemAccess().getEndKeyword_8());
		}
		(
			otherlv_12='fuzzysetcollection'
			{
				newLeafNode(otherlv_12, grammarAccess.getSimpleSystemAccess().getFuzzysetcollectionKeyword_9_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getSimpleSystemAccess().getFuzzysetFuzzySetParserRuleCall_9_1_0());
					}
					lv_fuzzyset_13_0=ruleFuzzySet
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
						}
						add(
							$current,
							"fuzzyset",
							lv_fuzzyset_13_0,
							"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.FuzzySet");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getSimpleSystemAccess().getFuzzysetFuzzySetParserRuleCall_9_2_0());
					}
					lv_fuzzyset_14_0=ruleFuzzySet
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
						}
						add(
							$current,
							"fuzzyset",
							lv_fuzzyset_14_0,
							"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.FuzzySet");
						afterParserOrEnumRuleCall();
					}
				)
			)*
			otherlv_15='endfuzzyset'
			{
				newLeafNode(otherlv_15, grammarAccess.getSimpleSystemAccess().getEndfuzzysetKeyword_9_3());
			}
		)?
		otherlv_16='ruleset'
		{
			newLeafNode(otherlv_16, grammarAccess.getSimpleSystemAccess().getRulesetKeyword_10());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSimpleSystemAccess().getRulesetRuleSetParserRuleCall_11_0());
				}
				lv_ruleset_17_0=ruleRuleSet
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
					}
					add(
						$current,
						"ruleset",
						lv_ruleset_17_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.RuleSet");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getSimpleSystemAccess().getRulesetRuleSetParserRuleCall_12_0());
				}
				lv_ruleset_18_0=ruleRuleSet
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
					}
					add(
						$current,
						"ruleset",
						lv_ruleset_18_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.RuleSet");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_19='endruleset'
		{
			newLeafNode(otherlv_19, grammarAccess.getSimpleSystemAccess().getEndrulesetKeyword_13());
		}
		otherlv_20='actions'
		{
			newLeafNode(otherlv_20, grammarAccess.getSimpleSystemAccess().getActionsKeyword_14());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSimpleSystemAccess().getActiondefinitionActionParserRuleCall_15_0());
				}
				lv_actiondefinition_21_0=ruleAction
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
					}
					add(
						$current,
						"actiondefinition",
						lv_actiondefinition_21_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.Action");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getSimpleSystemAccess().getActiondefinitionActionParserRuleCall_16_0());
				}
				lv_actiondefinition_22_0=ruleAction
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
					}
					add(
						$current,
						"actiondefinition",
						lv_actiondefinition_22_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.Action");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_23='endactions'
		{
			newLeafNode(otherlv_23, grammarAccess.getSimpleSystemAccess().getEndactionsKeyword_17());
		}
		(
			otherlv_24='variables'
			{
				newLeafNode(otherlv_24, grammarAccess.getSimpleSystemAccess().getVariablesKeyword_18_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getSimpleSystemAccess().getVariableConVariableParserRuleCall_18_1_0());
					}
					lv_variable_25_0=ruleConVariable
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
						}
						add(
							$current,
							"variable",
							lv_variable_25_0,
							"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.ConVariable");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getSimpleSystemAccess().getVariableConVariableParserRuleCall_18_2_0());
					}
					lv_variable_26_0=ruleConVariable
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
						}
						add(
							$current,
							"variable",
							lv_variable_26_0,
							"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.ConVariable");
						afterParserOrEnumRuleCall();
					}
				)
			)*
			otherlv_27='endvariables'
			{
				newLeafNode(otherlv_27, grammarAccess.getSimpleSystemAccess().getEndvariablesKeyword_18_3());
			}
		)?
		otherlv_28='transitions'
		{
			newLeafNode(otherlv_28, grammarAccess.getSimpleSystemAccess().getTransitionsKeyword_19());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSimpleSystemAccess().getTransitionTransitionParserRuleCall_20_0());
				}
				lv_transition_29_0=ruleTransition
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
					}
					add(
						$current,
						"transition",
						lv_transition_29_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.Transition");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getSimpleSystemAccess().getTransitionTransitionParserRuleCall_21_0());
				}
				lv_transition_30_0=ruleTransition
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimpleSystemRule());
					}
					add(
						$current,
						"transition",
						lv_transition_30_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.Transition");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_31='endtransitions'
		{
			newLeafNode(otherlv_31, grammarAccess.getSimpleSystemAccess().getEndtransitionsKeyword_22());
		}
		otherlv_32='begin'
		{
			newLeafNode(otherlv_32, grammarAccess.getSimpleSystemAccess().getBeginKeyword_23());
		}
		otherlv_33='startlocation'
		{
			newLeafNode(otherlv_33, grammarAccess.getSimpleSystemAccess().getStartlocationKeyword_24());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSimpleSystemRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getSimpleSystemAccess().getStartlocationLocationCrossReference_25_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_35='errorlocation'
		{
			newLeafNode(otherlv_35, grammarAccess.getSimpleSystemAccess().getErrorlocationKeyword_26());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSimpleSystemRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getSimpleSystemAccess().getErrorlocationLocationCrossReference_27_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_37='endsystem'
		{
			newLeafNode(otherlv_37, grammarAccess.getSimpleSystemAccess().getEndsystemKeyword_28());
		}
	)
;

// Entry rule entryRuleConVariable
entryRuleConVariable returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getConVariableRule()); }
	iv_ruleConVariable=ruleConVariable
	{ $current=$iv_ruleConVariable.current; }
	EOF;

// Rule ConVariable
ruleConVariable returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getConVariableAccess().getContinuousVariableParserRuleCall_0());
		}
		this_ContinuousVariable_0=ruleContinuousVariable
		{
			$current = $this_ContinuousVariable_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getConVariableAccess().getClockParserRuleCall_1());
		}
		this_Clock_1=ruleClock
		{
			$current = $this_Clock_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleContinuousVariable
entryRuleContinuousVariable returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getContinuousVariableRule()); }
	iv_ruleContinuousVariable=ruleContinuousVariable
	{ $current=$iv_ruleContinuousVariable.current; }
	EOF;

// Rule ContinuousVariable
ruleContinuousVariable returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getContinuousVariableAccess().getVariableAction_0(),
					$current);
			}
		)
		otherlv_1='variable'
		{
			newLeafNode(otherlv_1, grammarAccess.getContinuousVariableAccess().getVariableKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getContinuousVariableAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getContinuousVariableRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleClock
entryRuleClock returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getClockRule()); }
	iv_ruleClock=ruleClock
	{ $current=$iv_ruleClock.current; }
	EOF;

// Rule Clock
ruleClock returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getClockAccess().getClockAction_0(),
					$current);
			}
		)
		otherlv_1='clock'
		{
			newLeafNode(otherlv_1, grammarAccess.getClockAccess().getClockKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getClockAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getClockRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleFuzzySet
entryRuleFuzzySet returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getFuzzySetRule()); }
	iv_ruleFuzzySet=ruleFuzzySet
	{ $current=$iv_ruleFuzzySet.current; }
	EOF;

// Rule FuzzySet
ruleFuzzySet returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getFuzzySetAccess().getFuzzySetAction_0(),
					$current);
			}
		)
		otherlv_1='fuzzysets'
		{
			newLeafNode(otherlv_1, grammarAccess.getFuzzySetAccess().getFuzzysetsKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getFuzzySetAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getFuzzySetRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getFuzzySetAccess().getMembershipfunctionMembershipFunctionParserRuleCall_3_0());
				}
				lv_membershipfunction_3_0=ruleMembershipFunction
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getFuzzySetRule());
					}
					add(
						$current,
						"membershipfunction",
						lv_membershipfunction_3_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.MembershipFunction");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getFuzzySetAccess().getMembershipfunctionMembershipFunctionParserRuleCall_4_0());
				}
				lv_membershipfunction_4_0=ruleMembershipFunction
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getFuzzySetRule());
					}
					add(
						$current,
						"membershipfunction",
						lv_membershipfunction_4_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.MembershipFunction");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_5='end'
		{
			newLeafNode(otherlv_5, grammarAccess.getFuzzySetAccess().getEndKeyword_5());
		}
	)
;

// Entry rule entryRuleMembershipFunction
entryRuleMembershipFunction returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMembershipFunctionRule()); }
	iv_ruleMembershipFunction=ruleMembershipFunction
	{ $current=$iv_ruleMembershipFunction.current; }
	EOF;

// Rule MembershipFunction
ruleMembershipFunction returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getMembershipFunctionAccess().getLambdaParserRuleCall_0());
		}
		this_Lambda_0=ruleLambda
		{
			$current = $this_Lambda_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getMembershipFunctionAccess().getTrapezoidParserRuleCall_1());
		}
		this_Trapezoid_1=ruleTrapezoid
		{
			$current = $this_Trapezoid_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getMembershipFunctionAccess().getAlphaParserRuleCall_2());
		}
		this_Alpha_2=ruleAlpha
		{
			$current = $this_Alpha_2.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleAlpha
entryRuleAlpha returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAlphaRule()); }
	iv_ruleAlpha=ruleAlpha
	{ $current=$iv_ruleAlpha.current; }
	EOF;

// Rule Alpha
ruleAlpha returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getAlphaAccess().getAlphaAction_0(),
					$current);
			}
		)
		otherlv_1='alpha'
		{
			newLeafNode(otherlv_1, grammarAccess.getAlphaAccess().getAlphaKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAlphaAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAlphaRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='on'
		{
			newLeafNode(otherlv_3, grammarAccess.getAlphaAccess().getOnKeyword_3());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAlphaRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getAlphaAccess().getVariableVariableCrossReference_4_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5='('
		{
			newLeafNode(otherlv_5, grammarAccess.getAlphaAccess().getLeftParenthesisKeyword_5());
		}
		(
			(
				lv_a_6_0=RULE_DOUBLE
				{
					newLeafNode(lv_a_6_0, grammarAccess.getAlphaAccess().getADOUBLETerminalRuleCall_6_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAlphaRule());
					}
					setWithLastConsumed(
						$current,
						"a",
						lv_a_6_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.DOUBLE");
				}
			)
		)
		otherlv_7=','
		{
			newLeafNode(otherlv_7, grammarAccess.getAlphaAccess().getCommaKeyword_7());
		}
		(
			(
				lv_b_8_0=RULE_DOUBLE
				{
					newLeafNode(lv_b_8_0, grammarAccess.getAlphaAccess().getBDOUBLETerminalRuleCall_8_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAlphaRule());
					}
					setWithLastConsumed(
						$current,
						"b",
						lv_b_8_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.DOUBLE");
				}
			)
		)
		otherlv_9=')'
		{
			newLeafNode(otherlv_9, grammarAccess.getAlphaAccess().getRightParenthesisKeyword_9());
		}
	)
;

// Entry rule entryRuleLambda
entryRuleLambda returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLambdaRule()); }
	iv_ruleLambda=ruleLambda
	{ $current=$iv_ruleLambda.current; }
	EOF;

// Rule Lambda
ruleLambda returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getLambdaAccess().getLambdaAction_0(),
					$current);
			}
		)
		otherlv_1='lambda'
		{
			newLeafNode(otherlv_1, grammarAccess.getLambdaAccess().getLambdaKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getLambdaAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLambdaRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='on'
		{
			newLeafNode(otherlv_3, grammarAccess.getLambdaAccess().getOnKeyword_3());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLambdaRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getLambdaAccess().getVariableVariableCrossReference_4_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5='('
		{
			newLeafNode(otherlv_5, grammarAccess.getLambdaAccess().getLeftParenthesisKeyword_5());
		}
		(
			(
				lv_a_6_0=RULE_DOUBLE
				{
					newLeafNode(lv_a_6_0, grammarAccess.getLambdaAccess().getADOUBLETerminalRuleCall_6_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLambdaRule());
					}
					setWithLastConsumed(
						$current,
						"a",
						lv_a_6_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.DOUBLE");
				}
			)
		)
		otherlv_7=','
		{
			newLeafNode(otherlv_7, grammarAccess.getLambdaAccess().getCommaKeyword_7());
		}
		(
			(
				lv_u_8_0=RULE_DOUBLE
				{
					newLeafNode(lv_u_8_0, grammarAccess.getLambdaAccess().getUDOUBLETerminalRuleCall_8_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLambdaRule());
					}
					setWithLastConsumed(
						$current,
						"u",
						lv_u_8_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.DOUBLE");
				}
			)
		)
		otherlv_9=','
		{
			newLeafNode(otherlv_9, grammarAccess.getLambdaAccess().getCommaKeyword_9());
		}
		(
			(
				lv_b_10_0=RULE_DOUBLE
				{
					newLeafNode(lv_b_10_0, grammarAccess.getLambdaAccess().getBDOUBLETerminalRuleCall_10_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLambdaRule());
					}
					setWithLastConsumed(
						$current,
						"b",
						lv_b_10_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.DOUBLE");
				}
			)
		)
		otherlv_11=')'
		{
			newLeafNode(otherlv_11, grammarAccess.getLambdaAccess().getRightParenthesisKeyword_11());
		}
	)
;

// Entry rule entryRuleTrapezoid
entryRuleTrapezoid returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTrapezoidRule()); }
	iv_ruleTrapezoid=ruleTrapezoid
	{ $current=$iv_ruleTrapezoid.current; }
	EOF;

// Rule Trapezoid
ruleTrapezoid returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getTrapezoidAccess().getTrapezoidAction_0(),
					$current);
			}
		)
		otherlv_1='trapezoid'
		{
			newLeafNode(otherlv_1, grammarAccess.getTrapezoidAccess().getTrapezoidKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTrapezoidAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTrapezoidRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='on'
		{
			newLeafNode(otherlv_3, grammarAccess.getTrapezoidAccess().getOnKeyword_3());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTrapezoidRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getTrapezoidAccess().getVariableVariableCrossReference_4_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5='('
		{
			newLeafNode(otherlv_5, grammarAccess.getTrapezoidAccess().getLeftParenthesisKeyword_5());
		}
		(
			(
				lv_a_6_0=RULE_DOUBLE
				{
					newLeafNode(lv_a_6_0, grammarAccess.getTrapezoidAccess().getADOUBLETerminalRuleCall_6_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTrapezoidRule());
					}
					setWithLastConsumed(
						$current,
						"a",
						lv_a_6_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.DOUBLE");
				}
			)
		)
		otherlv_7=','
		{
			newLeafNode(otherlv_7, grammarAccess.getTrapezoidAccess().getCommaKeyword_7());
		}
		(
			(
				lv_b_8_0=RULE_DOUBLE
				{
					newLeafNode(lv_b_8_0, grammarAccess.getTrapezoidAccess().getBDOUBLETerminalRuleCall_8_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTrapezoidRule());
					}
					setWithLastConsumed(
						$current,
						"b",
						lv_b_8_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.DOUBLE");
				}
			)
		)
		otherlv_9=')'
		{
			newLeafNode(otherlv_9, grammarAccess.getTrapezoidAccess().getRightParenthesisKeyword_9());
		}
	)
;

// Entry rule entryRuleRuleSet
entryRuleRuleSet returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRuleSetRule()); }
	iv_ruleRuleSet=ruleRuleSet
	{ $current=$iv_ruleRuleSet.current; }
	EOF;

// Rule RuleSet
ruleRuleSet returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getRuleSetAccess().getDiscreteEventRulesetParserRuleCall_0());
		}
		this_DiscreteEventRuleset_0=ruleDiscreteEventRuleset
		{
			$current = $this_DiscreteEventRuleset_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getRuleSetAccess().getContinuousEventRuleSetParserRuleCall_1());
		}
		this_ContinuousEventRuleSet_1=ruleContinuousEventRuleSet
		{
			$current = $this_ContinuousEventRuleSet_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleDiscreteEventRuleset
entryRuleDiscreteEventRuleset returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDiscreteEventRulesetRule()); }
	iv_ruleDiscreteEventRuleset=ruleDiscreteEventRuleset
	{ $current=$iv_ruleDiscreteEventRuleset.current; }
	EOF;

// Rule DiscreteEventRuleset
ruleDiscreteEventRuleset returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getDiscreteEventRulesetAccess().getDiscreteEventRulesetAction_0(),
					$current);
			}
		)
		otherlv_1='discreteeventruleset'
		{
			newLeafNode(otherlv_1, grammarAccess.getDiscreteEventRulesetAccess().getDiscreteeventrulesetKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDiscreteEventRulesetAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDiscreteEventRulesetRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_3='discreteevents'
			{
				newLeafNode(otherlv_3, grammarAccess.getDiscreteEventRulesetAccess().getDiscreteeventsKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getDiscreteEventRulesetAccess().getDiscreteeventDiscreteEventParserRuleCall_3_1_0());
					}
					lv_discreteevent_4_0=ruleDiscreteEvent
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getDiscreteEventRulesetRule());
						}
						add(
							$current,
							"discreteevent",
							lv_discreteevent_4_0,
							"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.DiscreteEvent");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_5=','
				{
					newLeafNode(otherlv_5, grammarAccess.getDiscreteEventRulesetAccess().getCommaKeyword_3_2_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getDiscreteEventRulesetAccess().getDiscreteeventDiscreteEventParserRuleCall_3_2_1_0());
						}
						lv_discreteevent_6_0=ruleDiscreteEvent
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getDiscreteEventRulesetRule());
							}
							add(
								$current,
								"discreteevent",
								lv_discreteevent_6_0,
								"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.DiscreteEvent");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
		otherlv_7='endevents'
		{
			newLeafNode(otherlv_7, grammarAccess.getDiscreteEventRulesetAccess().getEndeventsKeyword_4());
		}
		otherlv_8='endruleset'
		{
			newLeafNode(otherlv_8, grammarAccess.getDiscreteEventRulesetAccess().getEndrulesetKeyword_5());
		}
	)
;

// Entry rule entryRuleContinuousEventRuleSet
entryRuleContinuousEventRuleSet returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getContinuousEventRuleSetRule()); }
	iv_ruleContinuousEventRuleSet=ruleContinuousEventRuleSet
	{ $current=$iv_ruleContinuousEventRuleSet.current; }
	EOF;

// Rule ContinuousEventRuleSet
ruleContinuousEventRuleSet returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getContinuousEventRuleSetAccess().getContinuousEventRulesetAction_0(),
					$current);
			}
		)
		otherlv_1='continouseventruleset'
		{
			newLeafNode(otherlv_1, grammarAccess.getContinuousEventRuleSetAccess().getContinouseventrulesetKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getContinuousEventRuleSetAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getContinuousEventRuleSetRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='rules'
		{
			newLeafNode(otherlv_3, grammarAccess.getContinuousEventRuleSetAccess().getRulesKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getContinuousEventRuleSetAccess().getRuleRuleParserRuleCall_4_0());
				}
				lv_rule_4_0=ruleRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getContinuousEventRuleSetRule());
					}
					add(
						$current,
						"rule",
						lv_rule_4_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.Rule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getContinuousEventRuleSetAccess().getRuleRuleParserRuleCall_5_0());
				}
				lv_rule_5_0=ruleRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getContinuousEventRuleSetRule());
					}
					add(
						$current,
						"rule",
						lv_rule_5_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.Rule");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_6='endrules'
		{
			newLeafNode(otherlv_6, grammarAccess.getContinuousEventRuleSetAccess().getEndrulesKeyword_6());
		}
		otherlv_7='endruleset'
		{
			newLeafNode(otherlv_7, grammarAccess.getContinuousEventRuleSetAccess().getEndrulesetKeyword_7());
		}
	)
;

// Entry rule entryRuleDiscreteEvent
entryRuleDiscreteEvent returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDiscreteEventRule()); }
	iv_ruleDiscreteEvent=ruleDiscreteEvent
	{ $current=$iv_ruleDiscreteEvent.current; }
	EOF;

// Rule DiscreteEvent
ruleDiscreteEvent returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getDiscreteEventAccess().getDiscreteEventAction_0(),
					$current);
			}
		)
		otherlv_1='discreteevent'
		{
			newLeafNode(otherlv_1, grammarAccess.getDiscreteEventAccess().getDiscreteeventKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDiscreteEventAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDiscreteEventRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleRule
entryRuleRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRuleRule()); }
	iv_ruleRule=ruleRule
	{ $current=$iv_ruleRule.current; }
	EOF;

// Rule Rule
ruleRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getRuleAccess().getFuzzyRuleParserRuleCall_0());
		}
		this_FuzzyRule_0=ruleFuzzyRule
		{
			$current = $this_FuzzyRule_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getRuleAccess().getCrispGuardParserRuleCall_1());
		}
		this_CrispGuard_1=ruleCrispGuard
		{
			$current = $this_CrispGuard_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleCrispGuard
entryRuleCrispGuard returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getCrispGuardRule()); }
	iv_ruleCrispGuard=ruleCrispGuard
	{ $current=$iv_ruleCrispGuard.current; }
	EOF;

// Rule CrispGuard
ruleCrispGuard returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getCrispGuardAccess().getCrispGuardAction_0(),
					$current);
			}
		)
		otherlv_1='crisprule'
		{
			newLeafNode(otherlv_1, grammarAccess.getCrispGuardAccess().getCrispruleKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getCrispGuardAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getCrispGuardRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3=':='
		{
			newLeafNode(otherlv_3, grammarAccess.getCrispGuardAccess().getColonEqualsSignKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getCrispGuardAccess().getRelationexpressionRelationExpressionParserRuleCall_4_0());
				}
				lv_relationexpression_4_0=ruleRelationExpression
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getCrispGuardRule());
					}
					set(
						$current,
						"relationexpression",
						lv_relationexpression_4_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.RelationExpression");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleRelationExpression
entryRuleRelationExpression returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRelationExpressionRule()); }
	iv_ruleRelationExpression=ruleRelationExpression
	{ $current=$iv_ruleRelationExpression.current; }
	EOF;

// Rule RelationExpression
ruleRelationExpression returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getRelationExpressionAccess().getGreaterExpressionParserRuleCall_0());
		}
		this_GreaterExpression_0=ruleGreaterExpression
		{
			$current = $this_GreaterExpression_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getRelationExpressionAccess().getLessExpressionParserRuleCall_1());
		}
		this_LessExpression_1=ruleLessExpression
		{
			$current = $this_LessExpression_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleGreaterExpression
entryRuleGreaterExpression returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getGreaterExpressionRule()); }
	iv_ruleGreaterExpression=ruleGreaterExpression
	{ $current=$iv_ruleGreaterExpression.current; }
	EOF;

// Rule GreaterExpression
ruleGreaterExpression returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getGreaterExpressionAccess().getGreaterExpressionAction_0(),
					$current);
			}
		)
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getGreaterExpressionRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getGreaterExpressionAccess().getVariableVariableCrossReference_1_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='>'
		{
			newLeafNode(otherlv_2, grammarAccess.getGreaterExpressionAccess().getGreaterThanSignKeyword_2());
		}
		(
			(
				lv_c_3_0=RULE_DOUBLE
				{
					newLeafNode(lv_c_3_0, grammarAccess.getGreaterExpressionAccess().getCDOUBLETerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getGreaterExpressionRule());
					}
					setWithLastConsumed(
						$current,
						"c",
						lv_c_3_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.DOUBLE");
				}
			)
		)
	)
;

// Entry rule entryRuleLessExpression
entryRuleLessExpression returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLessExpressionRule()); }
	iv_ruleLessExpression=ruleLessExpression
	{ $current=$iv_ruleLessExpression.current; }
	EOF;

// Rule LessExpression
ruleLessExpression returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getLessExpressionAccess().getLessExpressionAction_0(),
					$current);
			}
		)
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLessExpressionRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getLessExpressionAccess().getVariableVariableCrossReference_1_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='<'
		{
			newLeafNode(otherlv_2, grammarAccess.getLessExpressionAccess().getLessThanSignKeyword_2());
		}
		(
			(
				lv_c_3_0=RULE_DOUBLE
				{
					newLeafNode(lv_c_3_0, grammarAccess.getLessExpressionAccess().getCDOUBLETerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLessExpressionRule());
					}
					setWithLastConsumed(
						$current,
						"c",
						lv_c_3_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.DOUBLE");
				}
			)
		)
	)
;

// Entry rule entryRuleFuzzyRule
entryRuleFuzzyRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getFuzzyRuleRule()); }
	iv_ruleFuzzyRule=ruleFuzzyRule
	{ $current=$iv_ruleFuzzyRule.current; }
	EOF;

// Rule FuzzyRule
ruleFuzzyRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getFuzzyRuleAccess().getFuzzyRuleAction_0(),
					$current);
			}
		)
		otherlv_1='fuzzyrule'
		{
			newLeafNode(otherlv_1, grammarAccess.getFuzzyRuleAccess().getFuzzyruleKeyword_1());
		}
		otherlv_2='end'
		{
			newLeafNode(otherlv_2, grammarAccess.getFuzzyRuleAccess().getEndKeyword_2());
		}
	)
;

// Entry rule entryRuleLocation
entryRuleLocation returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLocationRule()); }
	iv_ruleLocation=ruleLocation
	{ $current=$iv_ruleLocation.current; }
	EOF;

// Rule Location
ruleLocation returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getLocationAccess().getLocationAction_0(),
					$current);
			}
		)
		otherlv_1='location'
		{
			newLeafNode(otherlv_1, grammarAccess.getLocationAccess().getLocationKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getLocationAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLocationRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_3='do'
			{
				newLeafNode(otherlv_3, grammarAccess.getLocationAccess().getDoKeyword_3_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getLocationRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getLocationAccess().getCyclicactionActionDefinitionCrossReference_3_1_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_5='end'
		{
			newLeafNode(otherlv_5, grammarAccess.getLocationAccess().getEndKeyword_4());
		}
	)
;

// Entry rule entryRuleTransition
entryRuleTransition returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTransitionRule()); }
	iv_ruleTransition=ruleTransition
	{ $current=$iv_ruleTransition.current; }
	EOF;

// Rule Transition
ruleTransition returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getTransitionAccess().getTransitionAction_0(),
					$current);
			}
		)
		otherlv_1='transition'
		{
			newLeafNode(otherlv_1, grammarAccess.getTransitionAccess().getTransitionKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTransitionAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTransitionRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3=':'
		{
			newLeafNode(otherlv_3, grammarAccess.getTransitionAccess().getColonKeyword_3());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTransitionRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getTransitionAccess().getSourceLocationCrossReference_4_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5='->'
		{
			newLeafNode(otherlv_5, grammarAccess.getTransitionAccess().getHyphenMinusGreaterThanSignKeyword_5());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTransitionRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getTransitionAccess().getTargetLocationCrossReference_6_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_7='trigger'
		{
			newLeafNode(otherlv_7, grammarAccess.getTransitionAccess().getTriggerKeyword_7());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTransitionRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getTransitionAccess().getTriggerDiscreteEventCrossReference_8_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_9='action'
			{
				newLeafNode(otherlv_9, grammarAccess.getTransitionAccess().getActionKeyword_9_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getTransitionRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getTransitionAccess().getActiondefinitionActionDefinitionCrossReference_9_1_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_11='invariant'
			{
				newLeafNode(otherlv_11, grammarAccess.getTransitionAccess().getInvariantKeyword_10_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getTransitionRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getTransitionAccess().getInvariantRuleCrossReference_10_1_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
	)
;

// Entry rule entryRuleAction
entryRuleAction returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getActionRule()); }
	iv_ruleAction=ruleAction
	{ $current=$iv_ruleAction.current; }
	EOF;

// Rule Action
ruleAction returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getActionAccess().getActionDefinitionAction_0(),
					$current);
			}
		)
		otherlv_1='action'
		{
			newLeafNode(otherlv_1, grammarAccess.getActionAccess().getActionKeyword_1());
		}
		otherlv_2='name'
		{
			newLeafNode(otherlv_2, grammarAccess.getActionAccess().getNameKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getActionAccess().getNameEStringParserRuleCall_3_0());
				}
				lv_name_3_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getActionRule());
					}
					set(
						$current,
						"name",
						lv_name_3_0,
						"hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_4='reset'
			{
				newLeafNode(otherlv_4, grammarAccess.getActionAccess().getResetKeyword_4_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getActionRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getActionAccess().getResetClockCrossReference_4_1_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
	)
;

// Entry rule entryRuleEString
entryRuleEString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEStringRule()); }
	iv_ruleEString=ruleEString
	{ $current=$iv_ruleEString.current.getText(); }
	EOF;

// Rule EString
ruleEString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_STRING_0=RULE_STRING
		{
			$current.merge(this_STRING_0);
		}
		{
			newLeafNode(this_STRING_0, grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0());
		}
		    |
		this_ID_1=RULE_ID
		{
			$current.merge(this_ID_1);
		}
		{
			newLeafNode(this_ID_1, grammarAccess.getEStringAccess().getIDTerminalRuleCall_1());
		}
	)
;

RULE_DOUBLE : ('0'..'9')+ '.' ('0'..'9')+;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
