/*
 * generated by Xtext 2.21.0
 */
package hu.sze.aut.fuzzy.hybrid.system.ui.tests;

import com.google.inject.Injector;
import hu.sze.aut.fuzzy.hybrid.system.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class FuzzyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("hu.sze.aut.fuzzy.hybrid.system.FuzzyDsl");
	}

}
