<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statepubsubmodel" nsURI="http://jkk.sze.hu/statepubsubmodel"
    nsPrefix="statepubsubmodel">
  <eClassifiers xsi:type="ecore:EClass" name="MiddlewareNetwork">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="#//Node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" upperBound="-1"
        eType="#//Topic" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topicmessage" upperBound="-1"
        eType="#//TopicMessage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" lowerBound="1" eType="#//Node"
        eOpposite="#//Node/inputport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="continousState" upperBound="-1"
        eType="#//ContinousState" eOpposite="#//ContinousState/receivesFrom"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" eType="#//Topic"
        eOpposite="#//Topic/portTo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" lowerBound="1" eType="#//Node"
        eOpposite="#//Node/outputport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="continousState" eType="#//ContinousState"
        eOpposite="#//ContinousState/producesTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" eType="#//Topic"
        eOpposite="#//Topic/portFrom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputport" upperBound="-1"
        eType="#//OutputPort" containment="true" eOpposite="#//OutputPort/node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputport" upperBound="-1"
        eType="#//InputPort" containment="true" eOpposite="#//InputPort/node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="continousstate" upperBound="-1"
        eType="#//ContinousState" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopicMessage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TopicMessage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portTo" upperBound="-1"
        eType="#//InputPort" eOpposite="#//InputPort/topic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portFrom" eType="#//OutputPort"
        eOpposite="#//OutputPort/topic"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topic_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContinousState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="producesTo" upperBound="-1"
        eType="#//OutputPort" eOpposite="#//OutputPort/continousState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivesFrom" upperBound="-1"
        eType="#//InputPort" eOpposite="#//InputPort/continousState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
