/*
 * generated by Xtext 2.21.0
 */
package hu.sze.aut.fuzzy.hybrid.system;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FuzzyDslRuntimeModule extends AbstractFuzzyDslRuntimeModule {
}
