/*
 * generated by Xtext 2.21.0
 */
package hu.sze.aut.fuzzy.hybrid.system;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FuzzyDslStandaloneSetup extends FuzzyDslStandaloneSetupGenerated {

	public static void doSetup() {
		new FuzzyDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
