/*
 * generated by Xtext 2.21.0
 */
package hu.sze.aut.fuzzy.hybrid.system.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FuzzyDslUiModule extends AbstractFuzzyDslUiModule {

	public FuzzyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
