<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="robotdescriptionpackage" nsURI="http://inf.mit.bme.hu/testing/robot/description/package"
    nsPrefix="description">
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//Link" eOpposite="#//Link/sensor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="update_rate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Laser" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range_min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range_max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angle_min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angle_max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rangemeas" eType="#//RangeMeas"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rangeprop" eType="#//RangeProp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="samples" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution_distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" lowerBound="1" eType="#//Topic"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Odometry" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pose" lowerBound="1" eType="#//ROS_Pose"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="twist" lowerBound="1" eType="#//ROS_Twist"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Camera" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name_ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CameraType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cameraparameters" lowerBound="1"
        eType="#//CameraParameters" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Robot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" upperBound="-1"
        eType="#//Sensor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1" eType="#//Link"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joint" upperBound="-1"
        eType="#//Joint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="material" upperBound="-1"
        eType="#//Material" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transmission" upperBound="-1"
        eType="#//Transmission" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globals" eType="#//Globals"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" upperBound="-1"
        eType="#//Template" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametergroup" upperBound="-1"
        eType="#//ParameterGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simulator_type" upperBound="-1"
        eType="#//SimulatorType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plugin" upperBound="-1"
        eType="#//Plugin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeMeas">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" unique="false" upperBound="360"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Navigation" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" lowerBound="1"
        eType="#//Status" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goal" lowerBound="1" eType="#//Goal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feedback" eType="#//Feedback"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Status">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ROS_Pose" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feedback">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="current_pose" lowerBound="1"
        eType="#//ROS_Pose" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Planner" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" upperBound="-1" eType="#//ROS_Pose"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="planner_type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalPlanner" eSuperTypes="#//Planner"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocalPlanner" eSuperTypes="#//Planner"/>
  <eClassifiers xsi:type="ecore:EClass" name="ROS_Pose">
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" lowerBound="1"
        eType="#//ROS_Position" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orientation" lowerBound="1"
        eType="#//ROS_Orientation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROS_Position">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROS_Orientation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="w" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROS_Twist">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linear" lowerBound="1"
        eType="#//ROS_Linear" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="angular" lowerBound="1"
        eType="#//ROS_Angular" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROS_Angular">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROS_Linear">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//KinematicNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="joint" upperBound="-1"
        eType="#//Joint" eOpposite="#//Joint/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="axis" eType="#//Vec3" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Origin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inertial" eType="#//Inertial"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collision" upperBound="-1"
        eType="#//Collision" containment="true" eOpposite="#//Collision/link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visual" upperBound="-1"
        eType="#//Visual" containment="true" eOpposite="#//Visual/link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="material" eType="#//Material"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="#//Sensor"
        eOpposite="#//Sensor/link"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Joint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//Link" eOpposite="#//Link/joint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="axis" eType="#//Axis" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Origin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//JOINT_TYPE"
        defaultValueLiteral="FIXED"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//KinematicNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roottransformation" eType="#//Transformation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateinstantiation"
        eType="#//TemplateInstantiation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JOINT_TYPE">
    <eLiterals name="REVOLUTE"/>
    <eLiterals name="CONTINUOUS" value="1" literal="CONTINUOUS"/>
    <eLiterals name="PRISMATIC" value="2"/>
    <eLiterals name="FIXED" value="3"/>
    <eLiterals name="FLOATING" value="4"/>
    <eLiterals name="PLANAR" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vec3">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter_x" eType="#//FloatParameterField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter_y" eType="#//FloatParameterField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter_z" eType="#//FloatParameterField"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Origin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xyz" eType="#//Vec3" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rpy" eType="#//EulerRotation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EulerRotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pitch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yaw" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter_roll" eType="#//FloatParameterField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter_pitch" eType="#//FloatParameterField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter_yaw" eType="#//FloatParameterField"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inertial">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Origin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inertia" lowerBound="1"
        eType="#//Inertia" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Origin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geometry" eType="#//Geometry"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Visual" eSuperTypes="#//PhysicalDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" lowerBound="1" eType="#//Link"
        eOpposite="#//Link/visual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collision" eSuperTypes="#//PhysicalDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent_visual" eType="#//Visual"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" lowerBound="1" eType="#//Link"
        eOpposite="#//Link/collision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Geometry" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Box" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter_width" eType="#//FloatParameterField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter_depth" eType="#//FloatParameterField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter_height" eType="#//FloatParameterField"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cylinder" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter_radius" eType="#//FloatParameterField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter_length" eType="#//FloatParameterField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sphere" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mesh" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sclae" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inertia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ixx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ixy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iyy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iyz" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ixz" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="izz" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeProp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DepthCamera" eSuperTypes="#//Camera"/>
  <eClassifiers xsi:type="ecore:EClass" name="Material">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="red" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="green" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alpha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transmission">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuator" lowerBound="1"
        eType="#//Actuator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="transmission_interface/SimpleTransmission"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardwareinterface" lowerBound="1"
        eType="#//HardwareInterface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pidparameters" lowerBound="1"
        eType="#//PIDParameters" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mechanicalreduction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HardwareInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="joint" lowerBound="1" eType="#//Joint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardwareInterface" eType="#//EnumHardwareInterfaces"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumHardwareInterfaces">
    <eLiterals name="VELOCITY_CONTROLLER"/>
    <eLiterals name="POSITION_CONTROLLER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FloatParameter" eSuperTypes="#//Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterField" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FloatParameterField" eSuperTypes="#//ParameterField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="divider" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Limit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limit_min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limit_max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="velocity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Globals">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0f"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Template">
    <eStructuralFeatures xsi:type="ecore:EReference" name="joint" upperBound="-1"
        eType="#//Joint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1" eType="#//Link"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transmission" upperBound="-1"
        eType="#//Transmission" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KinematicNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterGroup" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scale" eType="#//Scale"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rotate" eType="#//Rotate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="translation" eType="#//Translation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Translation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rotate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pitch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yaw" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scale">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sz" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateInstantiation" eSuperTypes="#//KinematicNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" eType="#//Template"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scale" eType="#//Scale"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SphericalJoint" eSuperTypes="#//Joint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="axis2" eType="#//Axis"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="axis3" eType="#//Axis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Axis" eSuperTypes="#//Vec3">
    <eStructuralFeatures xsi:type="ecore:EReference" name="limit" eType="#//Limit"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMU" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rate_drift" lowerBound="1"
        eType="#//Vec3" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="acceldrift" lowerBound="1"
        eType="#//Vec3" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headinggaussiannoise" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" lowerBound="1" eType="#//Topic"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PIDParameters">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="d" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimulatorType">
    <eLiterals name="GAZEBO"/>
    <eLiterals name="BULLET" value="1"/>
    <eLiterals name="NONE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plugin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lidar" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertical_angle_limit" lowerBound="1"
        eType="#//AngleLimit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="horizontal_angle_limit"
        lowerBound="1" eType="#//AngleLimit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rangeprop" lowerBound="1"
        eType="#//RangeProp" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngleLimit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min_angle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_angle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sample" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GNSS" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="geolocation" lowerBound="1"
        eType="#//GeoLocation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeoLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CameraType">
    <eLiterals name="RGB"/>
    <eLiterals name="DEPTH" value="1"/>
    <eLiterals name="STEREO" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CameraParameters">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clip_near" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clip_far" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontal_fov" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
